# Generated by Django 5.2.14 on 2026-06-02 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Custody Management', max_length=200, verbose_name='Company Name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Company Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tax_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Registration')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='Currency')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='Default Language')),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Default Tax %')),
                ('receipt_footer', models.TextField(blank=True, null=True, verbose_name='Receipt Footer')),
                ('label_size', models.CharField(default='50x30', max_length=20, verbose_name='Label Size')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Deposit Number')),
                ('barcode_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Barcode Image')),
                ('visitor_name', models.CharField(max_length=200, verbose_name='Visitor Name')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('national_id', models.CharField(max_length=50, verbose_name='National ID / Passport')),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check-In Date')),
                ('expected_pickup_date', models.DateField(blank=True, null=True, verbose_name='Expected Pickup Date')),
                ('description', models.TextField(verbose_name='Deposit Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('storage_location', models.CharField(choices=[('shelf_a1', 'Shelf A1'), ('shelf_a2', 'Shelf A2'), ('shelf_b1', 'Shelf B1'), ('shelf_b2', 'Shelf B2'), ('shelf_c1', 'Shelf C1'), ('shelf_c2', 'Shelf C2'), ('vault', 'Vault'), ('cold_storage', 'Cold Storage')], default='shelf_a1', max_length=50, verbose_name='Storage Location')),
                ('shelf_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shelf Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='draft', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_deposits', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='custody.deposit')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepositPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='custody.deposit')),
            ],
            options={
                'verbose_name': 'Deposit Photo',
                'verbose_name_plural': 'Deposit Photos',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('position', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('storage', 'Storage Staff')], max_length=100, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custody.employee', verbose_name='Assigned Employee'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Invoice Number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Tax %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='custody.deposit')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.CharField(max_length=200, verbose_name='Service Item')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='custody.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
