# Generated by Django 5.2.14 on 2026-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_customer_deposit_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Deposit Fee'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deposit_fee_description',
            field=models.CharField(default='Deposit Service Fee', max_length=200, verbose_name='Fee Description'),
        ),
    ]
