# Generated by Django 5.2.14 on 2026-06-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0003_systemsettings_deposit_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(max_length=50, unique=True, verbose_name='Box/Unit Number')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('location_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location Area')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Storage Box',
                'verbose_name_plural': 'Storage Boxes',
                'ordering': ['box_number'],
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='storage_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='custody.storagebox', verbose_name='Storage Box'),
        ),
    ]
