# Generated by Django 5.2.14 on 2026-06-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0004_storagebox_deposit_storage_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Rental Duration (days)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='encrypted_reference',
            field=models.TextField(blank=True, help_text='Cryptographically signed booking reference for QR', null=True, verbose_name='Encrypted Reference'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rental End Date'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='item_type',
            field=models.CharField(choices=[('small', 'Small (phone/wallet)'), ('medium', 'Medium (bag/laptop)'), ('large', 'Large (suitcase/box)'), ('extra_large', 'Extra Large (furniture)')], default='medium', max_length=20, verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_token',
            field=models.CharField(blank=True, help_text='One-time token for payment gateway redirect', max_length=100, null=True, verbose_name='Payment Token'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rental Start Date'),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='item_type',
            field=models.CharField(choices=[('small', 'Small (phone/wallet)'), ('medium', 'Medium (bag/laptop)'), ('large', 'Large (suitcase/box)'), ('extra_large', 'Extra Large (furniture)')], default='medium', help_text='What size item fits this box', max_length=20, verbose_name='Fits Item Type'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Gateway Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('gateway', models.CharField(default='mock', max_length=50, verbose_name='Payment Gateway')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Response')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='custody.deposit', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('small', 'Small (phone/wallet)'), ('medium', 'Medium (bag/laptop)'), ('large', 'Large (suitcase/box)'), ('extra_large', 'Extra Large (furniture)')], max_length=20, verbose_name='Item Type')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration (days)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['item_type', 'duration_days'],
                'unique_together': {('item_type', 'duration_days')},
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custody.pricingrule', verbose_name='Applied Pricing'),
        ),
    ]
